# Generated by Django 5.0.1 on 2024-04-17 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodBank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Venue', models.CharField(max_length=200, null=True)),
                ('Pincode', models.CharField(max_length=200, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='donor',
            name='Sex',
            field=models.CharField(choices=[('Male', 'Male'), ('FemaleFemale', 'Female'), ('Transgender', 'Transgender')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='unit_status',
            field=models.CharField(choices=[('Donated', 'Donated'), ('Tested and Processed', 'Tested and Processed'), ('Available for transfusion', 'Available for transfusion'), ('Utilized', 'Utilized')], default='Donated', max_length=50),
        ),
        migrations.AlterField(
            model_name='donor',
            name='Age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='donor',
            name='Bloodgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='donor',
            name='Email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='Phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
