# Generated by Django 5.0.1 on 2024-04-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodBank', '0004_alter_donor_unit_status'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
