# Generated by Django 5.0.1 on 2024-04-20 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodBank', '0006_donationdrive_created_by_donor_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='profile_pic',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BloodBank.donationdrive')),
            ],
        ),
        migrations.CreateModel(
            name='BloodPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BloodBank.group')),
            ],
        ),
    ]
