# Generated by Django 5.0.1 on 2024-04-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloodBank', '0007_remove_donor_profile_pic_group_bloodpacket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='DriveGroup',
        ),
        migrations.DeleteModel(
            name='BloodPacket',
        ),
    ]
