# Generated by Django 5.0.1 on 2024-04-25 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodBank', '0009_alter_donor_rfid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RFID', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='donor',
            name='RFID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BloodBank.rfidtag'),
        ),
    ]
