# Generated by Django 5.0.1 on 2024-04-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodBank', '0010_rfidtag_alter_donor_rfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='unit_status',
            field=models.CharField(choices=[('Donated', 'Donated'), ('Tested and Processed', 'Tested and Processed'), ('Available for Transfusion', 'Available for Transfusion'), ('Utilized', 'Utilized'), ('Transferred to main bank', 'Transferred to main bank')], default='Donated', max_length=50),
        ),
    ]
