# Generated by Django 5.0.1 on 2024-05-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodBank', '0011_alter_donor_unit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidtag',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
